# Generated by Django 4.2.7 on 2023-12-11 16:59

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandCaruselBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=20, verbose_name='Наименование Сети.')),
                ('is_video', models.BooleanField(default=False)),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Ссылка для видео')),
                ('image', models.ImageField(blank=True, null=True, upload_to='carousel/')),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Тайтл Рус.')),
                ('title_en', models.CharField(max_length=100, verbose_name='Тайтл Англ.')),
                ('title_kk', models.CharField(max_length=100, verbose_name='Тайтл Каз.')),
                ('content_ru', models.TextField(verbose_name='Крнтент Рус')),
                ('content_en', models.TextField(verbose_name='Крнтент Англ')),
                ('content_kk', models.TextField(verbose_name='Крнтент Каз')),
                ('image', models.ImageField(upload_to='carousel_images/', verbose_name='Изображение')),
                ('seo', models.CharField(max_length=100, verbose_name='SEO текст')),
            ],
        ),
        migrations.CreateModel(
            name='GeographyBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='icons/')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название на Рус.')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название на Англ.')),
                ('name_kk', models.CharField(max_length=100, verbose_name='Название на Каз.')),
                ('branch', models.IntegerField(verbose_name='Кол-во филиалов')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='Дата')),
                ('content_ru', models.TextField(verbose_name='Контент Рус')),
                ('content_en', models.TextField(verbose_name='Контент Англ')),
                ('content_kk', models.TextField(verbose_name='Контент Каз')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Наименование роли партнера')),
            ],
        ),
        migrations.CreateModel(
            name='SEOtxt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo', models.TextField(verbose_name='Тест для SEO')),
            ],
        ),
        migrations.CreateModel(
            name='StatBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supermarket', models.IntegerField(verbose_name='Кол-во Супермаркетов')),
                ('year', models.IntegerField(verbose_name='Лет на рынке')),
                ('employee', models.IntegerField(verbose_name='Кол-во Сотрудников')),
                ('sklad', models.IntegerField(verbose_name='Площать Складов')),
                ('square_all', models.IntegerField(verbose_name='Общая площадь')),
                ('square_mart', models.IntegerField(verbose_name='Торговая площадь')),
            ],
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_ru_b1', models.TextField(verbose_name='Крнтент Рус блок 1')),
                ('content_ru_b2', models.TextField(verbose_name='Крнтент Рус блок 2')),
                ('content_en_b1', models.TextField(verbose_name='Крнтент Англ блок 1')),
                ('content_en_b2', models.TextField(verbose_name='Крнтент Англ блок 2')),
                ('content_kk_b1', models.TextField(verbose_name='Крнтент Каз блок 1')),
                ('content_kk_b2', models.TextField(verbose_name='Крнтент Каз блок 2')),
            ],
        ),
        migrations.CreateModel(
            name='PartnershipApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=100, null=True)),
                ('message', models.TextField(verbose_name='Текст Обращения')),
                ('partner_file', models.FileField(blank=True, null=True, upload_to='partner_file/')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnership_apps', to='leading.partnerrole')),
            ],
        ),
    ]
